### ISSUE TITLE
CI Needs Updating

### ISSUE THREAD

**Issue by MatejGolian** [MatejGolian/ReaHotkey#17]
AutoHotkey 2.0.12 has been released. @Timtam, could you update the CI, please?
And I'd also like to ask. It's not enough to just change the numbers in ci.yaml, right? You also have to make changes in your builder branch. Is that correct?

**Comment by Timtam** [comment]
Nope, changing the numbers in ci.yaml should be enough unless they 
changed something on where they store their download location or 
something.


------ Originalnachricht ------
Von "MatejGolian" ***@***.***>
An "MatejGolian/ReaHotkey" ***@***.***>
Cc "Toni Barth" ***@***.***>; "Mention" 
***@***.***>
Datum 06.04.2024 11:32:17
Betreff [MatejGolian/ReaHotkey] CI Needs Updating (Issue #17)

**Comment by MatejGolian** [comment]
Thanks, good to know that it's that simple.
BTW, on the workflow run page under Annotations it states the following:
"1 warning
build
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, robinraju/release-downloader@v1.8, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."
Is that anything we should be concerned about, perhaps in the foreseeable future?

**Comment by Timtam** [comment]
It'll be a problem at some point, but not yet.


------ Originalnachricht ------
Von "MatejGolian" ***@***.***>
An "MatejGolian/ReaHotkey" ***@***.***>
Cc "Toni Barth" ***@***.***>; "Mention" 
***@***.***>
Datum 06.04.2024 12:04:17
Betreff Re: [MatejGolian/ReaHotkey] CI Needs Updating (Issue #17)

**Comment by MatejGolian** [comment]
I thought so.
There's one more unrelated thing I wanted to ask your opinion about.
The changelog for AutoHotkey 2.0.11 states:
"Added a workaround for the first shown menu not accepting keyboard input on Windows 10."
I haven't tried it, but maybe it solves the native AHK menu focusing problem we have been experiencing before. If that is the case, perhaps AccessiblePluginMenu and AccessibleStandaloneMenu could be removed, although on the other hand keeping them in there does no harm and they could still be useful as an alternative.
Any thoughts?
And to be honest, I've spent quite some time coding them, so that's another reason why I'm hesitant to get rid of them just like that... 🙂

**Comment by Timtam** [comment]
I'd say try changing one AccessibleMenu back to a typical context menu 
and see for a while if it works or not, and if it does, we can 
transition back to them step by step if we want to, but can still keep 
your version around because why not, maybe it will become useful later 
again.


------ Originalnachricht ------
Von "MatejGolian" ***@***.***>
An "MatejGolian/ReaHotkey" ***@***.***>
Cc "Toni Barth" ***@***.***>; "Mention" 
***@***.***>
Datum 06.04.2024 12:21:43
Betreff Re: [MatejGolian/ReaHotkey] CI Needs Updating (Issue #17)

**Comment by MatejGolian** [comment]
I only really used one menu in the Kontakt library chooser so, I did just what you suggested.
It seems to work fine, but of course we'll see.
Either way thanks for the input.
I'll close this for now... 🙂
