### ISSUE TITLE
Builds Failing

### ISSUE THREAD

**Issue by MatejGolian** [MatejGolian/ReaHotkey#8]
There is a × symbol in the ReadMe. Is it perhaps because of that?
Also, AutoHotkey v2.0.11 is out.

**Comment by Timtam** [comment]
Yep, that one was the culprid. I'm pretty sure that it's allowed to have those there, but the document wasn't properly encoded as UTF-8. I just replaced it with an "x" and now it works again. I also updated to AHK 2.0.11.
